apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-service-dataplane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-service-dataplane
  template:
    metadata:
      labels:
        app: fake-service-dataplane
    spec:
      containers:
      - name: fake-service-dataplane
        image: nicholasjackson/fake-service:v0.26.0 
        ports:
        - containerPort: 9090
      - name: consul-dataplane
        image: hashicorp/consul-dataplane
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
        volumeMounts:
        - name: certs-volume
          mountPath: /consul/certs
        command:
          - "/usr/local/bin/dumb-init"
          - "/usr/local/bin/consul-dataplane"
          - "-addresses=consul-service.consul-dc1.svc"
          - "-service-node-name=fake-service-dataplane"
          - "-proxy-service-id=1"
          - "-ca-certs=/consul/certs/consul-agent-ca.pem"
          - "-ca-certs=/consul/certs/dc1-server-consul-0.pem"
          - "-grpc-port=8502"
          - "-log-level=trace"
      volumes:
      - name: certs-volume
        secret:
          secretName: consul-certs
---
apiVersion: v1
kind: Service
metadata:
  name: fake-service-dataplane
  labels:
    app: fake-service-dataplane
spec:
  selector:
    app: fake-service-dataplane
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090