apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-server-config
data:
  consul-config.hcl: |
    data_dir = "/opt/consul"

    server = true
    
    encrypt = "qDOPBEr+/oUVeOFQOnVypxwDaHzLrD+lvjo5vCEBbZ0="
    
    ui_config {
      enabled = true
    }

    tls {
      defaults {
          ca_file = "/consul/certs/consul-agent-ca.pem"
          cert_file = "/consul/certs/dc1-server-consul-0.pem"
          key_file = "/consul/certs/dc1-server-consul-0-key.pem"

          verify_incoming = true
          verify_outgoing = true
      }
    }

    auto_encrypt {
      allow_tls = true
    }

    retry_join = ["consul-serf-lan.consul-dc1.svc:8301"]
    bootstrap_expect = 3