apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-server-config
data:
  consul-config.hcl: |
    data_dir = "/opt/consul"

    server = true

    log_level = "TRACE"
    
    encrypt = "qDOPBEr+/oUVeOFQOnVypxwDaHzLrD+lvjo5vCEBbZ0="

    bind_addr =  "0.0.0.0"

    retry_join = ["consul-serf-lan.consul-dc1.svc:8301"]
    
    bootstrap_expect = 1
    
    ui_config {
      enabled = true
    }

    tls {
      grpc {
          verify_incoming = false
      }
      defaults {
          ca_file = "/consul/certs/consul-agent-ca.pem"
          cert_file = "/consul/certs/dc1-server-consul-0.pem"
          key_file = "/consul/certs/dc1-server-consul-0-key.pem"

          verify_incoming = true
          verify_outgoing = true
      }
    }

    ports {
      grpc = -1
      grpc_tls = 8502
    }

    auto_encrypt {
      allow_tls = true
    }

    connect {
      enabled = true
    }