apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: hashicorp/consul-enterprise
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
        volumeMounts:
        - name: certs-volume
          mountPath: /consul/certs
        - name: config-volume
          mountPath: /consul/config
        env:
        - name: CONSUL_LICENSE
          valueFrom:
            secretKeyRef:
              name: consul-ent-license
              key: key
        command:
          - "consul"
          - "agent"
          - "-config-file=/consul/config/consul-config.hcl"
          - "-datacenter=dc1"
        ports:
        - containerPort: 8500  # Consul HTTP API
        - containerPort: 8600  # Consul DNS
        - containerPort: 8300  # Consul server RPC
        - containerPort: 8301  # Consul server serf LAN
        - containerPort: 8302  # Consul server serf WAN
        - containerPort: 8502  # Consul GRPC API
      volumes:
      - name: certs-volume
        secret:
          secretName: consul-certs
      - name: config-volume
        configMap:
          name: consul-server-config
          items:
          - key: consul-config.hcl
            path: consul-config.hcl
---
apiVersion: v1
kind: Service
metadata:
  name: consul-http
  labels:
    app: consul
spec:
  selector:
    app: consul
  ports:
  - protocol: TCP
    port: 8500
    targetPort: 8500
---
apiVersion: v1
kind: Service
metadata:
  name: consul-dns
  labels:
    app: consul
spec:
  selector:
    app: consul
  ports:
  - protocol: UDP
    port: 8600
    targetPort: 8600
---
apiVersion: v1
kind: Service
metadata:
  name: consul-rpc
  labels:
    app: consul
spec:
  selector:
    app: consul
  ports:
  - protocol: TCP
    port: 8300
    targetPort: 8300
---
apiVersion: v1
kind: Service
metadata:
  name: consul-serf-lan
  labels:
    app: consul
spec:
  selector:
    app: consul
  ports:
  - protocol: TCP
    port: 8301
    targetPort: 8301
---
apiVersion: v1
kind: Service
metadata:
  name: consul-serf-wan
  labels:
    app: consul
spec:
  selector:
    app: consul
  ports:
  - protocol: TCP
    port: 8302
    targetPort: 8302
---
apiVersion: v1
kind: Service
metadata:
  name: consul-grpc
  labels:
    app: consul
spec:
  selector:
    app: consul
  ports:
  - protocol: TCP
    port: 8502
    targetPort: 8502
