apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fake-service
  template:
    metadata:
      labels:
        app: fake-service
    spec:
      containers:
      - name: fake-service
        image: nicholasjackson/fake-service:v0.26.0 
        ports:
        - containerPort: 9090
      - name: consul
        image: hashicorp/consul-enterprise
        volumeMounts:
        - name: certs-volume
          mountPath: /consul/certs
        - name: config-volume
          mountPath: /consul/config
        env:
        - name: CONSUL_LICENSE
          valueFrom:
            secretKeyRef:
              name: consul-ent-license
              key: key
        command:
          - "consul"
          - "agent"
          - "-config-dir=/consul/config/"
          - "-datacenter=dc1"
        ports:
        - containerPort: 8500  # Consul HTTP API
        - containerPort: 8600  # Consul DNS
        - containerPort: 8300  # Consul server RPC
        - containerPort: 8301  # Consul server serf LAN
        - containerPort: 8302  # Consul server serf WAN
        - containerPort: 8502  # Consul HTTPS API
      volumes:
      - name: certs-volume
        secret:
          secretName: consul-certs
      - name: config-volume
        configMap:
          name: consul-fake-service-config
          items:
          - key: consul-config.hcl
            path: consul-config.hcl
          - key: service.hcl
            path: service.hcl
---
apiVersion: v1
kind: Service
metadata:
  name: fake-service
  labels:
    app: fake-service
spec:
  selector:
    app: fake-service
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090